#!/usr/bin/env bash
#This installs and configures HAproxy load balancer
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.8 -y
apt-get update -y
apt-get install haproxy=1.8.\* -y

echo -e "
frontend http
	bind *:80
	mode http
	default_backend web_servers
" >> /etc/haproxy/haproxy.cfg

echo -e "
backend web_servers
	balance roundrobin
	server 143742-web-01 54.159.1.9:80 check
	server 143742-web-02 54.89.135.176:80 check
" >> /etc/haproxy/haproxy.cfg
/etc/init.d/haproxy restart
